#!/bin/bash
# Fix WireGuard keys extraction using Python for reliability

set -e

cd /tmp

# Regenerate profile
echo "🔄 Regenerating WireGuard profile..."
wgcf generate --config /tmp/wgcf-account.toml --profile /tmp/wgcf-profile.conf

# Extract keys using Python (most reliable)
echo "📋 Extracting keys with Python..."
eval $(python3 << 'PYEOF'
import re
import base64
import sys

try:
    with open('/tmp/wgcf-profile.conf', 'r') as f:
        content = f.read()
except Exception as e:
    print(f"Error reading profile: {e}", file=sys.stderr)
    sys.exit(1)

# Extract keys using regex (strict base64 pattern)
private_match = re.search(r'^PrivateKey\s*=\s*([A-Za-z0-9+/=]{43,44})', content, re.MULTILINE)
public_match = re.search(r'^PublicKey\s*=\s*([A-Za-z0-9+/=]{43,44})', content, re.MULTILINE)
preshared_match = re.search(r'^PresharedKey\s*=\s*([A-Za-z0-9+/=]*)', content, re.MULTILINE)
address_match = re.search(r'^Address\s*=\s*([^\s]+)', content, re.MULTILINE)
endpoint_match = re.search(r'^Endpoint\s*=\s*([^\s]+)', content, re.MULTILINE)

errors = []

if private_match:
    private_key = private_match.group(1).strip()
    try:
        decoded = base64.b64decode(private_key, validate=True)
        if len(decoded) == 32:  # WireGuard private key is 32 bytes
            print(f"export PRIVATE_KEY='{private_key}'")
        else:
            errors.append(f"PrivateKey wrong length: {len(decoded)} bytes (expected 32)")
    except Exception as e:
        errors.append(f"PrivateKey invalid base64: {e}")
else:
    errors.append("PrivateKey not found")

if public_match:
    public_key = public_match.group(1).strip()
    try:
        decoded = base64.b64decode(public_key, validate=True)
        if len(decoded) == 32:  # WireGuard public key is 32 bytes
            print(f"export PUBLIC_KEY='{public_key}'")
        else:
            errors.append(f"PublicKey wrong length: {len(decoded)} bytes (expected 32)")
    except Exception as e:
        errors.append(f"PublicKey invalid base64: {e}")
else:
    errors.append("PublicKey not found")

if preshared_match:
    preshared_key = preshared_match.group(1).strip()
    if preshared_key:
        try:
            decoded = base64.b64decode(preshared_key, validate=True)
            if len(decoded) == 32:  # Preshared key is 32 bytes
                print(f"export PRESHARED_KEY='{preshared_key}'")
            else:
                print("export PRESHARED_KEY=''")
        except:
            print("export PRESHARED_KEY=''")
    else:
        print("export PRESHARED_KEY=''")
else:
    print("export PRESHARED_KEY=''")

# Address can appear multiple times (IPv4 and IPv6), collect all
address_matches = re.findall(r'^Address\s*=\s*([^\s]+)', content, re.MULTILINE)
if address_matches:
    # Join all addresses with comma (WireGuard format)
    addresses = ','.join([addr.strip() for addr in address_matches])
    print(f"export ADDRESSES='{addresses}'")
else:
    errors.append("Address not found")

if endpoint_match:
    endpoint = endpoint_match.group(1).strip()
    print(f"export ENDPOINT='{endpoint}'")
else:
    errors.append("Endpoint not found")

if errors:
    for error in errors:
        print(f"ERROR: {error}", file=sys.stderr)
    sys.exit(1)
PYEOF
)

if [ $? -ne 0 ]; then
    echo "❌ Failed to extract keys"
    exit 1
fi

echo "✅ Keys extracted successfully"
echo "   Private: ${PRIVATE_KEY:0:20}... (${#PRIVATE_KEY} chars)"
echo "   Public: ${PUBLIC_KEY:0:20}... (${#PUBLIC_KEY} chars)"
echo "   Endpoint: ${ENDPOINT}"

# Resolve endpoint to IPv4
ENDPOINT_HOST=$(echo "${ENDPOINT}" | cut -d':' -f1)
ENDPOINT_PORT=$(echo "${ENDPOINT}" | cut -d':' -f2)
ENDPOINT_IP=$(dig +short -4 "${ENDPOINT_HOST}" | head -1)

if [ -z "${ENDPOINT_IP}" ]; then
    echo "❌ Failed to resolve ${ENDPOINT_HOST} to IPv4"
    exit 1
fi

echo "   Endpoint IP: ${ENDPOINT_IP}:${ENDPOINT_PORT}"

# Update .env
cd /opt/trailerio
TMDB_KEY=$(grep "^TMDB_API_KEY=" .env 2>/dev/null | cut -d= -f2 || echo "")

# Backup
cp .env .env.backup.$(date +%Y%m%d_%H%M%S)

# Write new .env
cat > .env <<ENVEOF
# TMDB API Key
TMDB_API_KEY=${TMDB_KEY:-bfe73358661a995b992ae9a812aa0d2f}

# Cloudflare Warp WireGuard Configuration (generated by fix-wireguard-keys.sh)
WIREGUARD_PRIVATE_KEY=${PRIVATE_KEY}
WIREGUARD_ADDRESSES=${ADDRESSES}
WIREGUARD_PUBLIC_KEY=${PUBLIC_KEY}
WIREGUARD_PRESHARED_KEY=${PRESHARED_KEY:-}
WIREGUARD_ENDPOINT_IP=${ENDPOINT_IP}
WIREGUARD_ENDPOINT_PORT=${ENDPOINT_PORT}

# Gluetun HTTP Proxy (for yt-dlp)
GLUETUN_HTTP_PROXY=http://gluetun:8000
ENVEOF

echo ""
echo "✅ Updated .env with validated keys"
echo ""
echo "🔄 Restarting gluetun..."
docker compose up -d gluetun
sleep 5
echo ""
echo "📋 Gluetun logs:"
docker compose logs gluetun --tail=40 | grep -E "(INFO|ERROR|VPN|connection|UP|DOWN|Wireguard|successfully|established)" || \
docker compose logs gluetun --tail=30

