#!/bin/bash
# Setup Cloudflare Warp for gluetun
# This script generates WireGuard keys using wgcf and adds them to .env

set -e

PROJECT_DIR="${1:-/opt/trailerio}"
ENV_FILE="${PROJECT_DIR}/.env"

echo "🔧 Setting up Cloudflare Warp for gluetun..."
echo "📁 Project directory: ${PROJECT_DIR}"

# Check if wgcf is installed
if ! command -v wgcf &> /dev/null; then
    echo "📥 Installing wgcf..."
    # Download wgcf for Linux
    WGCF_URL="https://github.com/ViRb3/wgcf/releases/latest/download/wgcf_linux_amd64"
    curl -L -o /tmp/wgcf "${WGCF_URL}" || {
        echo "❌ Failed to download wgcf"
        exit 1
    }
    chmod +x /tmp/wgcf
    mv /tmp/wgcf /usr/local/bin/wgcf 2>/dev/null || {
        # If /usr/local/bin is not writable, use /tmp
        echo "⚠️  Cannot install to /usr/local/bin, using /tmp/wgcf"
        WGCF_BIN="/tmp/wgcf"
    }
    WGCF_BIN="${WGCF_BIN:-/usr/local/bin/wgcf}"
else
    WGCF_BIN="wgcf"
fi

# Verify wgcf works
if ! ${WGCF_BIN} --version &>/dev/null; then
    echo "⚠️  wgcf --version failed, but continuing..."
fi

cd /tmp

# Register wgcf account (if not already registered)
ACCOUNT_FILE="/tmp/wgcf-account.toml"
if [ ! -f "${ACCOUNT_FILE}" ] || [ ! -s "${ACCOUNT_FILE}" ]; then
    echo "📝 Registering wgcf account..."
    ${WGCF_BIN} register --config "${ACCOUNT_FILE}" || {
        echo "❌ Failed to register wgcf account"
        exit 1
    }
    sleep 2
fi

# Generate WireGuard profile
echo "🔑 Generating WireGuard profile..."
PROFILE_FILE="/tmp/wgcf-profile.conf"
${WGCF_BIN} generate --config "${ACCOUNT_FILE}" --profile "${PROFILE_FILE}" || {
    echo "❌ Failed to generate WireGuard profile"
    exit 1
}

if [ ! -f "${PROFILE_FILE}" ] || [ ! -s "${PROFILE_FILE}" ]; then
    echo "❌ Profile file not found or empty"
    exit 1
fi

# Parse WireGuard config
echo "📋 Parsing WireGuard configuration..."

PRIVATE_KEY=$(grep "PrivateKey" "${PROFILE_FILE}" | cut -d'=' -f2 | tr -d ' ')
PUBLIC_KEY=$(grep "PublicKey" "${PROFILE_FILE}" | cut -d'=' -f2 | tr -d ' ')
PRESHARED_KEY=$(grep "PresharedKey" "${PROFILE_FILE}" | cut -d'=' -f2 | tr -d ' ')
ADDRESSES=$(grep "Address" "${PROFILE_FILE}" | cut -d'=' -f2 | tr -d ' ')
ENDPOINT=$(grep "Endpoint" "${PROFILE_FILE}" | cut -d'=' -f2 | tr -d ' ')

if [ -z "${ENDPOINT}" ]; then
    echo "❌ Failed to parse endpoint from profile"
    exit 1
fi

ENDPOINT_IP=$(echo "${ENDPOINT}" | cut -d':' -f1)
ENDPOINT_PORT=$(echo "${ENDPOINT}" | cut -d':' -f2)

# Backup existing .env
if [ -f "${ENV_FILE}" ]; then
    cp "${ENV_FILE}" "${ENV_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
    echo "💾 Backed up existing .env file"
fi

# Read existing TMDB key
TMDB_KEY=$(grep "^TMDB_API_KEY=" "${ENV_FILE}" 2>/dev/null | cut -d= -f2 || echo "")

# Write WireGuard keys to .env
echo "✍️  Writing WireGuard keys to .env..."

cat > "${ENV_FILE}" <<EOF
# TMDB API Key
TMDB_API_KEY=${TMDB_KEY:-bfe73358661a995b992ae9a812aa0d2f}

# Cloudflare Warp WireGuard Configuration (generated by setup-warp.sh)
WIREGUARD_PRIVATE_KEY=${PRIVATE_KEY}
WIREGUARD_ADDRESSES=${ADDRESSES}
WIREGUARD_PUBLIC_KEY=${PUBLIC_KEY}
WIREGUARD_PRESHARED_KEY=${PRESHARED_KEY}
WIREGUARD_ENDPOINT_IP=${ENDPOINT_IP}
WIREGUARD_ENDPOINT_PORT=${ENDPOINT_PORT}

# Gluetun HTTP Proxy (for yt-dlp)
GLUETUN_HTTP_PROXY=http://gluetun:8000
EOF

echo "✅ WireGuard keys written to ${ENV_FILE}"
echo ""
echo "📊 Configuration summary:"
echo "   Endpoint: ${ENDPOINT_IP}:${ENDPOINT_PORT}"
echo "   Addresses: ${ADDRESSES}"
echo ""
echo "🔄 Restarting gluetun container..."
cd "${PROJECT_DIR}"
docker compose up -d gluetun || echo "⚠️  Failed to start gluetun (may need to restart manually)"

echo ""
echo "✅ Setup complete! Check gluetun logs with:"
echo "   docker compose logs gluetun -f"

