#!/bin/bash
# Cloudflare Warp Setup Script
# Run this on your VPS to automatically configure Cloudflare Warp for yt-dlp

set -e

echo "=========================================="
echo "Cloudflare Warp Setup for TrailerIO"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "Please run as root or with sudo"
    exit 1
fi

# Step 1: Install wgcf
echo "[1/5] Installing wgcf..."
if ! command -v wgcf &> /dev/null; then
    echo "Downloading wgcf..."
    WGCF_VERSION=$(curl -s https://api.github.com/repos/ViRb3/wgcf/releases/latest | grep tag_name | cut -d '"' -f 4)
    ARCH=$(uname -m)
    if [ "$ARCH" = "x86_64" ]; then
        ARCH="amd64"
    elif [ "$ARCH" = "aarch64" ]; then
        ARCH="arm64"
    fi
    
    wget -q "https://github.com/ViRb3/wgcf/releases/latest/download/wgcf_${WGCF_VERSION#v}_linux_${ARCH}" -O /tmp/wgcf
    chmod +x /tmp/wgcf
    mv /tmp/wgcf /usr/local/bin/wgcf
    echo "✓ wgcf installed"
else
    echo "✓ wgcf already installed"
fi

# Step 2: Register with Cloudflare (if not already registered)
echo ""
echo "[2/5] Registering with Cloudflare Warp..."
cd /tmp
if [ ! -f "wgcf-account.toml" ]; then
    wgcf register
    echo "✓ Registered with Cloudflare Warp"
else
    echo "✓ Already registered (wgcf-account.toml exists)"
fi

# Step 3: Generate profile
echo ""
echo "[3/5] Generating WireGuard profile..."
if [ ! -f "wgcf-profile.conf" ]; then
    wgcf generate
    echo "✓ Profile generated"
else
    echo "✓ Profile already exists, regenerating..."
    wgcf generate
fi

# Step 4: Extract keys from profile
echo ""
echo "[4/5] Extracting WireGuard keys..."
PROFILE_FILE="/tmp/wgcf-profile.conf"

if [ ! -f "$PROFILE_FILE" ]; then
    echo "✗ Error: wgcf-profile.conf not found"
    exit 1
fi

# Extract values from wgcf-profile.conf
PRIVATE_KEY=$(grep "PrivateKey" "$PROFILE_FILE" | cut -d '=' -f 2 | tr -d ' ')
ADDRESS=$(grep "Address" "$PROFILE_FILE" | cut -d '=' -f 2 | tr -d ' ' | head -n 1)
PUBLIC_KEY=$(grep "PublicKey" "$PROFILE_FILE" | cut -d '=' -f 2 | tr -d ' ')
ENDPOINT=$(grep "Endpoint" "$PROFILE_FILE" | cut -d '=' -f 2 | tr -d ' ')
ENDPOINT_IP=$(echo "$ENDPOINT" | cut -d ':' -f 1)
ENDPOINT_PORT=$(echo "$ENDPOINT" | cut -d ':' -f 2)
PRESHARED_KEY=$(grep "PresharedKey" "$PROFILE_FILE" | cut -d '=' -f 2 | tr -d ' ' || echo "")

if [ -z "$PRIVATE_KEY" ] || [ -z "$PUBLIC_KEY" ] || [ -z "$ENDPOINT_IP" ]; then
    echo "✗ Error: Failed to extract keys from profile"
    exit 1
fi

echo "✓ Keys extracted successfully"

# Step 5: Update .env file
echo ""
echo "[5/5] Updating .env file..."

# Get the project directory (assumes script is run from project root or provide path)
PROJECT_DIR="${1:-/opt/trailerio}"
ENV_FILE="$PROJECT_DIR/.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "Creating .env file..."
    touch "$ENV_FILE"
fi

# Backup existing .env
if [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "$ENV_FILE.backup.$(date +%Y%m%d_%H%M%S)"
    echo "✓ Backed up existing .env file"
fi

# Remove old WireGuard entries if they exist
sed -i '/^WIREGUARD_/d' "$ENV_FILE" 2>/dev/null || true

# Remove old GLUETUN_HTTP_PROXY if exists
sed -i '/^GLUETUN_HTTP_PROXY=/d' "$ENV_FILE" 2>/dev/null || true

# Add new WireGuard configuration
cat >> "$ENV_FILE" << EOF

# Cloudflare Warp Configuration (generated by setup-cloudflare-warp.sh)
WIREGUARD_PRIVATE_KEY=$PRIVATE_KEY
WIREGUARD_ADDRESSES=$ADDRESS
WIREGUARD_PUBLIC_KEY=$PUBLIC_KEY
WIREGUARD_ENDPOINT_IP=$ENDPOINT_IP
WIREGUARD_ENDPOINT_PORT=$ENDPOINT_PORT
GLUETUN_HTTP_PROXY=http://gluetun:8000
EOF

if [ -n "$PRESHARED_KEY" ]; then
    echo "WIREGUARD_PRESHARED_KEY=$PRESHARED_KEY" >> "$ENV_FILE"
fi

echo "✓ .env file updated with WireGuard keys"
echo ""
echo "=========================================="
echo "Setup Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Review the .env file: cat $ENV_FILE"
echo "2. Restart services: cd $PROJECT_DIR && docker compose up -d"
echo "3. Check gluetun status: docker compose logs gluetun"
echo ""
echo "To test if Cloudflare Warp is working:"
echo "  docker compose exec gluetun wget -qO- https://ipinfo.io"
echo ""

